account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path
from . import views


app_name = 'account'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path(
        'tag/<slug:tag_slug>/',
        views.post_list,
        name='post_list_by_tag'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        '<int:post_id>/comment/',
        views.post_comment,
        name='post_comment'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/delete/',
        views.post_delete,
        name='post_delete'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

myblog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('blog/', include('blog.urls', namespace='blog')),
]

account/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth import get_user_model


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='Повторите пароль',
        widget=forms.PasswordInput
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Пароли не совпадают")
        return cd['password2']

account/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from .forms import LoginForm, UserRegistrationForm


@login_required
def dashboard(request):
    return render(
        request,
        'account/dashboard.html',
        {'section': 'dashboard'}
    )


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password']
            )
            new_user.save()
            return render(
                request,
                'account/register_done.html',
                {'new_user': new_user}
            )
    else:
        user_form = UserRegistrationForm()
    return render(
        request,
        'account/register.html',
        {'user_form': user_form}
    )

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <span class="logo"><a href="{% url "blog:post_list" %}">MyBlog</a></span>
      {% if request.user.is_authenticated %}
        <ul class="menu">
          <li {% if section == "post_list" %}class="selected"{% endif %}>
            <a href="{% url 'blog:post_list' %}">Все записи</a>
          </li>
          <li {% if section == "follow" %}class="selected"{% endif %}>
            <a href="{% url 'blog:follow_index' %}">Подписки</a>
          </li>
          <li  {% if section == "create" %}class="selected"{% endif %}> 
            <a href="{% url 'blog:post_create' %}">Новая запись</a>
          </li>
        </ul>
      {% endif %}
      <span class="user">
        {% if request.user.is_authenticated %}
          Hello {{ request.user.first_name|default:request.user.username }},
          <form action="{% url "account:logout" %}" method="post">
            <button type="submit">Logout</button>
            {% csrf_token %}
          </form>
        {% else %}
          <a href="{% url "account:login" %}">Войти</a>
          <a href="{% url "account:register" %}">Зарегистрироваться</a>
        {% endif %}
      </span>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
    <div id="sidebar">
      <h2>My blog</h2>
      <p>Это мой блог</p>
    </div>
  </body>
</html>