blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path(
        'tag/<slug:tag_slug>/',
        views.post_list,
        name='post_list_by_tag'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        '<int:post_id>/comment/',
        views.post_comment,
        name='post_comment'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/delete/',
        views.post_delete,
        name='post_delete'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

myblog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
import uuid
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


User = get_user_model()


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(
        max_length=250,
        unique_for_date='publish'
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status,
        default=Status.PUBLISHED
    )
    tags = TaggableManager()
    is_hidden = models.BooleanField(default=False)
    secret_key = models.UUIDField(default=uuid.uuid4, blank=True)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )

    def get_absolute_edit_url(self):
        return reverse(
            "blog:post_edit",
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )

    def get_absolute_delete_url(self):
        return reverse(
            "blog:post_delete",
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Комментарий автора {self.name} на пост {self.post}'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    def __str__(self):
        return f'{self.user} follows {self.author}'

blog/forms.py
from django import forms
from .models import Comment, Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'body', 'slug', 'tags')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from taggit.models import Tag

from .forms import CommentForm, PostForm
from .models import Follow, Post, User


class PostListView(ListView):
    """
    Альтернативное представление для отображения постов.
    """
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    """
    Альтернативное представление для отображения постов.
    """
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(
            Tag,
            slug=tag_slug
        )
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(
        request,
        'blog/post/list.html',
        {
            'posts': posts,
            'tag': tag,
            'section': 'post_list'
        }
    )


def post_detail(request, year, month, day, post):
    """
    Представления для отображения отдельного поста.
    """
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    comments = post.comments.filter(active=True)
    form = CommentForm()
    token = request.GET.get('token')
    if not post.is_hidden or str(post.secret_key) == token:
        return render(
            request,
            'blog/post/detail.html',
            {
                'post': post,
                'comments': comments,
                'form': form
            }
        )
    return HttpResponseForbidden('Этот пост доступен только по запросу')


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(
        request,
        'blog/post/comment.html',
        {
            'post': post,
            'form': form,
            'comment': comment
        }
    )


@login_required
def post_create(request):
    template = 'blog/post/create_post.html'
    form = PostForm(request.POST or None)
    context = {
        'form': form,
        'section': 'create'
    }
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect(f'/blog/profile/{post.author.username}/')
    return render(request, template, context)


@login_required
def post_edit(request, year, month, day, post):
    template = 'blog/post/create_post.html'
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    context = {
        'form': form,
        'post': post,
        'is_edit': True,
    }
    if request.user == post.author and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect(f'/blog/{post.publish.year}/{post.publish.month}/{post.publish.day}/{post.slug}')
    return render(request, template, context)


@login_required
def post_delete(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    if request.method == 'POST':
        post.delete()
        return redirect('blog:post_list')
    return render(
        request,
        'blog/post/post_delete_confirm.html',
        {'post': post}
    )


def profile(request, username):
    template = 'blog/post/profile.html'
    user = request.user
    author = get_object_or_404(User, username=username)
    following = (
        user.is_authenticated
        and Follow.objects.filter(user=user, author=author)
    )
    post_list = author.posts.all().order_by('author')
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post_number = post_list.count()
    context = {
        'page_obj': page_obj,
        'post_number': post_number,
        'author': author,
        'following': following,
    }
    return render(request, template, context)


@login_required
def follow_index(request):
    """Выводит посты авторов, на которых
       подписан текущий пользователь."""
    template = 'blog/post/follow.html'
    user = request.user
    post_list = Post.objects.filter(
        author__following__user=user
    )
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'section': 'follow'
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Делает подписку на автора."""
    user = request.user
    author = get_object_or_404(User, username=username)
    if author != user:
        user.follower.get_or_create(
            user=user,
            author=author
        )
    return redirect('blog:profile', username)


@login_required
def profile_unfollow(request, username):
    """Отписывает пользователя от автора."""
    user = request.user
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(
        user=user,
        author=author
    )
    if follow.exists():
        follow.delete()
    return redirect('blog:profile', username)

blog/templates/blog/post/comment.html
{% extends "base.html" %}
{% block title %}Добавить комментарий{% endblock %}
{% block content %}
  {% if comment %}
    <h2>Ваш комментарий был добавлен.</h2>
    <p><a href="{{ post.get_absolute_url }}">Назад к посту</a></p>
  {% else %}
    {% include "blog/post/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

blog/templates/blog/post/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-body">
              <div class="card-header">
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Добавить запись
                {% endif %}
              </div>
              {% if is_edit %}
              {% if request.user == post.author %}
              <form 
              method="post"
              enctype="multipart/form-data"
              action="{{ post.get_absolute_edit_url }}">
                {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Тема<span class="required text-danger" >*</span>
                  </label>
                  {{ form.title }}
                  <span class="helptext text-muted">Тема</span>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Слаг<span class="required text-danger" >*</span>
                  </label>
                  {{ form.slug }}
                  <span class="helptext text-muted">Слаг нового поста</span>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Текст поста<span class="required text-danger" >*</span>
                  </label>
                  {{ form.body }}
                  <span class="helptext text-muted">Текст поста</span>
                </div>
                <div class="form-group row my-3 p-3">
                <label for="id_group">Тэги:</label>
                {{ form.tags }}
                <span class="helptext text-muted">
                  Тэги:
                </span>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %} 
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
              </form>
              {% endif %}
              {% else %}
              {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endif %}
              <form 
              method="post"
              enctype="multipart/form-data"
              action="{% url 'blog:post_create' %}">
              {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Тема<span class="required text-danger" >*</span>
                  </label>
                  {{ form.title }}
                  <span class="helptext text-muted">Тема нового поста</span>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Слаг<span class="required text-danger" >*</span>
                  </label>
                  {{ form.slug }}
                  <span class="helptext text-muted">Слаг нового поста</span>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Текст поста<span class="required text-danger" >*</span>
                  </label>
                  {{ form.body }}
                  <span class="helptext text-muted">Текст нового поста</span>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_group">Тэги:</label>
                  {{ form.tags }}
                  <span class="helptext text-muted">
                    Тэги:
                  </span>
                </div>
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    <!--{% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}-->
                    Добавить
                  </button>
                </div>
            </form>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/post/detail.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
  <h1>{{ post.title }}</h1>
  {% if post.is_hidden %}
    <p><em>Этот пост скрыт и доступен только по ссылке</em></p>
  {% else %}
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
  <li class="list-group-item">
              <a href="{% url 'blog:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
            {{ post.body|linebreaks }}
            {% if request.user == post.author %}
            <a 
    class="btn btn-primary" 
    href="{{ post.get_absolute_edit_url }}">
      редактировать запись
    </a>
    <a 
    class="btn btn-primary" 
    href="{{ post.get_absolute_delete_url }}">
      удалить запись
    </a>
  {% endif %}
  {% with comments.count as total_comments %}
  <h2>
    Всего комментариев: {{ total_comments }} 
  </h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Комментарий {{ forloop.counter }} пользователя {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>Еще нет комментариев.</p>
    {% endfor %}
    {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

blog/templates/blog/post/follow.html
{% extends 'base.html' %}

{% block title %}
  Подписки пользователя {{ user.get_full_name }}
{% endblock %}

{% block content %}
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'blog:profile' post.author.username %}">
          все посты пользователя
      </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.body }}</p>
    <a href="{{ post.get_absolute_url }}">подробная информация</a>
    {% if post.group %}    
      <a href="{% url 'blog:group_list' post.group.slug %}">
        все записи группы
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  
  {% include 'pagination.html' with page=page_obj %}

{% endblock %}

blog/templates/blog/post/list.html
{% extends "base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
  <h1>My Blog</h1>
  {% if tag %}
    <h2>Посты с тегами "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="tags">
        Тэги: 
        {% for tag in post.tags.all %}
          <a href="{% url "blog:post_list_by_tag" tag.slug %}">
            {{ tag.name }}
          </a>{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/post_delete_confirm.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<h1>Вы уверены, что хотите удалить пост "{{ post.title }}"?</h1>
<form method="post">
    {% csrf_token %}
    <button class="btn btn-primary" type="submit">Да, удалить</button>
    <a href="{% url 'blog:post_list' %}">Отменить</a>
</form>
{% endblock %}

blog/templates/blog/post/profile.html
{% extends 'base.html' %}

{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}

{% block content %}
<div class="mb-5">        
    <h1>Все посты пользователя {{ post.author.username }} </h1>
    <h3>Всего постов: {{ post_number }} </h3> 
    {% if author != request.user %} 
    {% if following %}
    <a
    class="btn btn-lg btn-light"
    href="{% url 'blog:profile_unfollow' author.username %}" role="button"
    >
    Отписаться
</a>
{% else %}
<a
class="btn btn-lg btn-primary"
href="{% url 'blog:profile_follow' author.username %}" role="button"
>
Подписаться
</a>
{% endif %}
{% endif %} 
</div>
{% for post in page_obj %}
  <h2>{{ post.title }}</h2>
  <article>
    <ul>
      <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
      </li>
    </ul>
    <p>{{ post.body }}</p>
    <a href="{{ post.get_absolute_url }}">
      подробная информация 
    </a>
  </article>
  {% if not forloop.last %}<hr>{% endif %}
  <!-- Остальные посты. после последнего нет черты -->
{% endfor %}
  {% include 'pagination.html' with page=page_obj %} 
{% endblock %}